# ---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.enabled: "false"
xpack.management.enabled: "false"
# xpack.monitoring.elasticsearch.password: simpleweb
# xpack.monitoring.elasticsearch.username: simpleweb
# xpack.monitoring.elasticsearch.hosts: [ "http://es01:9200" ]

# path.data: "/usr/share/logstash/data"
